services:
    clouddrive.api:
        image: ${DOCKER_REGISTRY-}clouddriveapi
        container_name: clouddrive.api
        build:
            context: .
            dockerfile: src/Bootstrapper/CloudDrive.Api/Dockerfile
        ports:
            - "8080:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__CloudDrive=${ConnectionStrings__CloudDrive}
            - Jwt__SigningKey=${Jwt__SigningKey}
            - Seq__ServerUrl=http://clouddrive.seq:80
        depends_on:
            clouddrive.database:
                condition: service_healthy
            clouddrive.seq:
                condition: service_started
        restart: unless-stopped
    
    clouddrive.database:
        image: postgres:17
        container_name: clouddrive.database
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5433:5432"
        volumes:
            - ./.containers/database:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    clouddrive.seq:
        image: datalust/seq:latest
        container_name: clouddrive.seq
        environment:
            - ACCEPT_EULA=Y
            - SEQ_FIRSTRUN_NOAUTHENTICATION=True
        ports:
            - "5341:80"
        volumes:
            - ./.containers/seq:/data
        restart: unless-stopped
